language: node_js
node_js:
  - "10"
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_script:
  - npm install -g firebase-tools
script:
  # populate production environment variables (currently just firebase config)
  - if [[ "$TRAVIS_BRANCH" = production/* ]]; then echo "setting production env" && npm run config:prod; fi
  # build specific app
  - if [[ "$TRAVIS_BRANCH" = production/budget-tool ]]; then echo "building budget" && npm run build:budget; fi
deploy:
  - provider: script
    script: firebase deploy --only hosting:budget-tool
    skip_cleanup: true
    on:
      branch: production/budget-tool
